databases:
  - name: hotel-management-db
    databaseName: hotelmanagementdb
    user: hoteluser
    plan: free

services:
  - type: web
    name: hotel-management
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hotel_management.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-management-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4